# Generated by Django 3.1.1 on 2021-01-09 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField()),
                ('url', models.URLField()),
                ('score', models.IntegerField(default=100)),
                ('requires_id', models.BooleanField()),
                ('legacy_arc_score', models.CharField(choices=[('full_support', 'Fully accepts legacy ARC number in place of ROC ID'), ('separate_support', 'Accepts legacy ARC number in a separate UI (passport number, for instance)'), ('no_support', 'Does not accept Legacy ARC numbers')], max_length=50)),
                ('new_arc_score', models.CharField(choices=[('full_support', 'Fully accepts new ARC number in place of ROC ID'), ('separate_support', 'Accepts new ARC number in a separate UI (passport number, for instance)'), ('no_support', 'Does not accept new ARC numbers')], max_length=50)),
                ('service_score', models.CharField(choices=[('full_service', 'Provides same service to all users'), ('partial_service', 'A portion of features not available to non-citizens'), ('no_service', 'Denies service to non-citizens')], max_length=50)),
                ('registration_score', models.CharField(choices=[('online_registration', 'All users may register online'), ('offline_registration', 'Non-citizens require offline registration')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.category')),
            ],
        ),
    ]
