# Generated by Django 3.1.1 on 2021-01-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='legacy_arc_score',
            field=models.CharField(choices=[('legacy_arc_full_support', 'Fully accepts legacy ARC number in place of ROC ID'), ('legacy_arc_separate_support', 'Accepts legacy ARC number in a separate UI (passport number, for instance)'), ('legacy_arc_no_support', 'Does not accept legacy ARC numbers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='new_arc_score',
            field=models.CharField(choices=[('new_arc_full_support', 'Fully accepts new ARC number in place of ROC ID'), ('new_arc_separate_support', 'Accepts new ARC number in a separate UI (passport number, for instance)'), ('new_arc_no_support', 'Does not accept new ARC numbers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='registration_score',
            field=models.CharField(choices=[('registration_online', 'All users may register online using the same process'), ('registration_offline', 'Non-citizens require additional offline registration steps')], max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_score',
            field=models.CharField(choices=[('service_full', 'Provides same service to all users'), ('service_partial', 'A portion of features not available to non-citizens'), ('service_none', 'Denies all services to non-citizens')], max_length=50),
        ),
    ]
